### ISSUE TITLE
Running on my own dataset

### ISSUE THREAD

**Issue by Pratapabhay** [tum-vision/fastfusion#18]
Hi,
First of all Great work. It really helped me to understand things about fusion and 3D reconstruction. It was running very well on TUM-Dataset, then I tried running on my own data set. Data is not very accurate but it is good enough to give decent results. 
Unfortunately it is not working, it gives me the error "Erroneous Bounding Box of first frame: [1000000 1000000 1000000]-[-1000000 -1000000 -1000000]U[Q:0]" . I looked up in the code and understood how its working but still I was not able to rectify it.
Can someone please tell me what all things needed to be taken care of while running the program on personal dataset. Had someone tried it?

Thanks in Advance

**Comment by shadowver** [comment]
I had same issue. It seems my pz value is too high to run computeboundingbox(). How do you solve the problem?
