### ISSUE TITLE
Saving the 3D Model

### ISSUE THREAD

**Issue by Pratapabhay** [tum-vision/fastfusion#20]
Hi @franksteinbruecker @christiankerl ,
Great work with the project, though I am 3 years behind you guys.I could be technically wrong since I just have a gist of how algorithm works. I just wanted to ask, how to finally save the 3d model onto the disk. I am really not sure if QGLViewer is capable to do that, since it is used directly to view 3D scenes but not saving the scene(correct me if I am wrong). May be saving the complete octree?
Thanks in advance.

**Comment by vectorcrumb** [comment]
@Pratapabhay did you ever find a solution for this?
