### ISSUE TITLE
BOOST_JOIN failed

### ISSUE THREAD

**Issue by PercyPanJX** [tum-vision/fastfusion#24]
Hi does anyone know how to deal with the following installation problem?

When I run the 'make', it got the BOOST error. My desktop is Ubuntu 14.04 with Boost 1.58.0, cmake 3.5.1, and qt 4.8.7. Any advise would be appreciated.

[ 24%] Built target auxiliary
[ 36%] Built target geometryfusion_mipmap_cpu
[ 72%] Built target geometryfusion_aos
[ 80%] Built target camerautils
[ 84%] Generating moc_onlinefusionviewer.cxx
usr/include/boost/type_traits/detail/has_binary_operator.hp:50: Parse error at "BOOST_JOIN"
src/CMakeFiles/onlinefusion.dir/build.make:62: recipe for target 'src/moc_onlinefusionviewer.cxx' failed
make[2]: *** [src/moc_onlinefusionviewer.cxx] Error 1
CMakeFiles/Makefile2:96: recipe for target 'src/CMakeFiles/onlinefusion.dir/all' failed
make[1]: *** [src/CMakeFiles/onlinefusion.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nrupatunga** [comment]
@PercyPanJX did you solve this issue?

**Comment by sachinkum0009** [comment]
Same here any help

**Comment by PercyPanJX** [comment]
I think the project is too old to get any update.
