### ISSUE TITLE
GTK+ 2 & GTK 3 mix error

### ISSUE THREAD

**Issue by MeinLieberTanz** [tum-vision/fastfusion#3]
There is an error under Ubuntu 14.04 64-bit:

<i>Creating Viewer
(onlinefusion:25209): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap</i>

Could you please clarify - is it possible to use the application under Ubuntu 14.04?

Best regards,
Vitaly

**Comment by api55** [comment]
Hi, 
I can confirm that is possible to use the application under Ubuntu 14.04 64-bit, and I didn't get that error. Hopefully, someone will answer you with possible solutions to your error, I can only confirmed that I have it working under Ubuntu 64 bit. 

Regards,
Pablo

**Comment by MeinLieberTanz** [comment]
Hi Pablo,

Thank you for the answer. Could you please upload result of the command "pkg-config --libs gtk+-2.0 clutter-gtk-1.0 gthread-2.0"? I see "-lgtk-3" string in output for my PC, which says that some mix of GTK+2 and GTK+3 really exists. But may be I ought to reinstall my Ubuntu to solve the issue.

Best regards,
Vitaly

**Comment by api55** [comment]
Hi Vitaly,
I got the following

```
$ pkg-config --libs gtk+-2.0 clutter-gtk-1.0 gthread-2.0
Package clutter-gtk-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `clutter-gtk-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'clutter-gtk-1.0' found
$
```

Best regards,
Pablo

**Comment by MeinLieberTanz** [comment]
Hi Pablo,

Everything works fine on fresh installed Ubuntu 14.04 64-bit. Thank you very much for your support.

Best regards,
Vitaly
